# Generated by Django 5.1.3 on 2024-11-28 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_favoriteresume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='favorite_users',
            field=models.ManyToManyField(related_name='favorited_resumes', through='resumes.FavoriteResume', to=settings.AUTH_USER_MODEL),
        ),
    ]
